# Generated by Django 2.0.1 on 2018-03-17 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('user_img', models.CharField(default='static\\upload\\1.jpg', max_length=128)),
                ('username', models.CharField(default='', max_length=125, unique=True)),
                ('profile', models.CharField(default='这个人很神秘', max_length=500)),
                ('sex', models.CharField(default='未知', max_length=2)),
                ('occupation', models.CharField(default='007？', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=150)),
                ('device', models.CharField(max_length=16, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('favor_count', models.IntegerField(default=0)),
                ('favor', models.ManyToManyField(related_name='fc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('fans_uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('follower_uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=64)),
                ('summary', models.CharField(max_length=128, null=True)),
                ('content', models.CharField(max_length=10000, null=True)),
                ('url', models.CharField(default='', max_length=128)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('newType', models.IntegerField(choices=[(1, '热点动态'), (2, '创新教育'), (3, '竞赛活动'), (4, '咖啡馆')])),
                ('favor_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('collect', models.ManyToManyField(related_name='cnew', to=settings.AUTH_USER_MODEL)),
                ('favor', models.ManyToManyField(related_name='fnew', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='blog.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
