# Generated by Django 2.0.3 on 2018-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_is_authenticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authenticate',
            field=models.BooleanField(default=True),
        ),
    ]
