# Generated by Django 2.0.3 on 2018-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180402_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authenticate',
            field=models.BooleanField(default=False),
        ),
    ]
