# Generated by Django 2.0.2 on 2018-04-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180411_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('detail', models.CharField(default='', max_length=200)),
                ('maxnum', models.IntegerField()),
                ('nownum', models.IntegerField()),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teammate', models.ManyToManyField(related_name='tm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
