# Generated by Django 2.0.3 on 2018-04-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180403_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticate',
        ),
    ]
