# Generated by Django 2.0.3 on 2018-04-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_user_is_authent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authent',
        ),
    ]
