# Generated by Django 2.0.3 on 2018-04-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_user_is_authent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authenticate',
            field=models.BooleanField(default=False),
        ),
    ]
