# Generated by Django 2.0.3 on 2018-04-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_is_authenticate'),
        ('blog', '0004_auto_20180414_2148'),
    ]

    operations = [
    ]
