# Generated by Django 2.0.3 on 2018-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_merge_20180414_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modify_pwdForm',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('r_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='re_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='re_data',
            field=models.DateField(null=True),
        ),
    ]
