# Generated by Django 2.0.2 on 2018-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180414_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(default='', max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='newType',
            field=models.IntegerField(choices=[(1, '热点动态'), (2, '创新教育'), (3, '咖啡馆')]),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='ts', to='blog.Tags'),
        ),
    ]
