# Generated by Django 2.0.2 on 2018-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180417_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
