# Generated by Django 2.0.2 on 2018-04-18 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180418_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_dialogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team_zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('relate_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team_dialogue',
            name='relate_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Team_zone'),
        ),
    ]
