# Generated by Django 2.0.2 on 2018-04-18 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180418_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_dialogue',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_dialogue',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_zone',
            name='summary',
            field=models.CharField(default='空白~', max_length=100),
        ),
    ]
