# Generated by Django 2.0.2 on 2018-04-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180418_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_zone',
            name='relate_team',
        ),
        migrations.RemoveField(
            model_name='team_dialogue',
            name='relate_zone',
        ),
        migrations.AddField(
            model_name='team',
            name='captain_talk',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team_dialogue',
            name='relate_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Team'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team_zone',
        ),
    ]
