# Generated by Django 2.0.2 on 2018-04-18 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180418_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_dialogue',
            name='uid',
        ),
        migrations.AddField(
            model_name='team_dialogue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_talk',
            field=models.CharField(default='无', max_length=200),
        ),
    ]
